roster/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('rosterman.roster.views',
    # Example:
    (r'^$', 'index'),
    (r'^(?P<team_id>\d+)/$', 'detail'),
    (r'^(?P<team_id>\d+)/add_player/$', 'add_player'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^rosterman/', include('rosterman.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
)

roster/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length="50")
    
    def __unicode__(self):
        return self.name
        

class Team(models.Model):
    name = models.CharField(max_length="50")
    city = models.ForeignKey(City)
    owner = models.CharField(max_length="100")
    founding_date = models.DateField('Founding Date')
    
    def __unicode__(self):
        return "%s %s" % (self.city, self.name)
    
class Player(models.Model):
    first_name = models.CharField(max_length="50")
    last_name = models.CharField(max_length="50")
    number = models.IntegerField()
    height = models.IntegerField()
    team = models.ForeignKey(Team)
    
    def __unicode__(self):
        return "%s %s" % (self.first_name,self.last_name)

roster/views.py
from django.shortcuts import render_to_response, get_object_or_404
from roster.models import Team, Player
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.

def index(request):
    team_list = Team.objects.all().order_by('name')
    return render_to_response('roster/index.html', {'team_list': team_list})

def detail(request,team_id):
    t = get_object_or_404(Team, pk=team_id)
    return render_to_response('roster/detail.html', {'team': t})
    
def add_player(request,team_id):
    t = get_object_or_404(Team,pk=team_id)
    try:
        p = Player()
        p.first_name = request.POST['first_name']
        p.last_name = request.POST['last_name']
        p.number = request.POST['number']
        p.height = request.POST['height']
    except (KeyError):
        return render_to_response("roster/%d" % team_id, {
                                   'error_message' : "You forgot fields"})
    else:
        p.team = t
        p.save()
        return HttpResponseRedirect(reverse('roster',args=(team_id)))

templates/roster/detail.html
<h3>{{ team.name }}</h3>
<h4>{{ team.city }}</h4>
<ul>
{% for player in team.player_set.all %}
    <li>{{ player.first_name }} {{ player.last_name }}</li>
{% endfor %}
</ul>
<br />
<form action="add_player/" method="post">
    <label for="first_name">First Name</label><input type="text" name="first_name">
    <label for="last_name">Last Name<input type="text" name="last_name"><br />
    <label for="number">Jersey #</label><input type="text" name="number">
    <label for="height">Height</label><input type="text" name="height"><br />
    <input type="submit" value="Add">
</form>
<br />
<a href="/roster">Back</a>

templates/roster/index.html
{% if team_list %}
    <h2>Teams:</h2>
    <ul>
    {% for team in team_list %}
        <li><a href="{{ team.id }}/">{{ team.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No teams are available.</p>
{% endif %}